version: '3.8'

services:
  app:
    container_name: stream-channel-be
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - type: bind
        source: ./src
        target: /stream-channel-be/src
      - type: bind
        source: __tests__
        target: /stream-channel-be/__tests__
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    container_name: stream-channel-db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
