services:
  - name: stream-channel-be
    type: web
    runtime: docker
    branch: deploy
    dockerfilePath: ./docker/app/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stream-channel-db
          property: connectionString
    dockerCommand: >
      /bin/sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run build &&
      npm start"

databases:
  - name: stream-channel-db
    databaseName: stream_channel_db
    user: stream_channel_user
    plan: free